services:
  skincare.api:
    image: cleanarchitecture.presentation
    build:
      context: .
      dockerfile: src/CleanArchitecture.Presentation/Dockerfile
    ports: 
    - "8082:8080"
    - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/dbcon.env
    depends_on:
      # This change ensures the API waits for the database to be healthy
      skincare.db:
        condition: service_healthy 
  
  skincare.db:
    image: postgres:17
    container_name: skincare.db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=skincare
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - skincare-data:/var/lib/postgresql/data 
    # Add a healthcheck to ensure the database is ready for connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d skincare"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
volumes:
  skincare-data: