services:
  skincare.api:
    image: cleanarchitecture.presentation
    build:
      context: .
      dockerfile: src/CleanArchitecture.Presentation/Dockerfile
    ports: 
    - "8082:8080"
    - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/dbcon.env
    depends_on:
      - skincare.db
  
  skincare.db:
    image: postgres:17
    container_name: skincare.db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=skincare
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - skincare-data:/var/lib/postgresql/data 
  
volumes:
  skincare-data: